# Code used to analyze DoLa results

In [3]:
import os
import sys
project_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.append(project_dir)

import glob
import json
import pandas as pd
pd.set_option('display.max_rows', 100)
import numpy as np

from config import IMPLEMENTED_MODELS

# TFQA

### Analyze results2 directory

In [8]:
raw_results = []
dola_results_dir = '../DoLa/results2/tfqa/{model_name}'
for model_name in IMPLEMENTED_MODELS:
    model_results_dir = dola_results_dir.format(model_name=model_name)
    if not os.path.exists(model_results_dir):
        continue
    result_fps = sorted(glob.glob(os.path.join(
        model_results_dir, '*'
    )))
    for result_fp in result_fps:
        if 'layers' not in result_fp:
            result_name = os.path.basename(result_fp)[:-5]
            data = json.load(open(os.path.join(result_fp)))
            raw_results.append([model_name, result_name.split('-')[1], result_name.split('-')[3], result_name.split('-')[4], data['total_mc1'], data['total_mc2'], data['total_mc3']])
df = pd.DataFrame(raw_results, columns=['model_name', 'ln_type', 'alpha', 'buckets', 'mc1', 'mc2', 'mc3'])#.query('buckets == "baseline"')
print(df.model_name.unique())

for col in df.columns:
    if isinstance(df[col].iloc[0], float):
        df[col] = df[col].apply(lambda x: round(x, 4))

df#.query("model_name == 'llama2-70b'")#.query("buckets == '40,42,44,46,48,50,52,54,56,58,60,80'")

['pythia-6.9b' 'llama2-70b' 'llama3_0-70b' 'qwen2-72b']

,model_name,ln_type,alpha,buckets,mc1,mc2,mc3
0,pythia-6.9b,none,none,baseline,0.2252,0.3717,0.1787
1,pythia-6.9b,none,0.0,"0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32",0.2607,0.5253,0.2448
2,pythia-6.9b,none,0.1,"0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32",0.2301,0.4417,0.1796
3,pythia-6.9b,none,0.1,"0,2,4,6,8,10,12,14,16,32",0.2277,0.4213,0.1782
4,pythia-6.9b,none,0.1,"16,18,20,22,24,26,28,30,32",0.2093,0.5097,0.1848
5,pythia-6.9b,none,0.1,"8,10,12,14,16,18,20,22,24,32",0.2179,0.4213,0.1733
6,pythia-6.9b,none,0.25,"0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32",0.2007,0.4682,0.1671
7,pythia-6.9b,none,0.5,"0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32",0.2166,0.4981,0.1717
8,pythia-6.9b,none,0.75,"0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32",0.2154,0.5043,0.1763
9,pythia-6.9b,none,0.9,"0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32",0.2142,0.5133,0.1745
10,llama2-70b,none,none,baseline,0.3745,0.5358,0.2721
11,llama2-70b,none,0.0,"60,62,64,66,68,70,72,74,76,78,80",0.2962,0.5355,0.2996
12,llama2-70b,none,0.1,"0,2,4,6,8,10,12,14,16,18,20,80",0.3317,0.5503,0.2319
13,llama2-70b,none,0.1,"20,22,24,26,28,30,32,34,36,38,40,80",0.3305,0.5559,0.2339
14,llama2-70b,none,0.1,"40,42,44,46,48,50,52,54,56,58,60,80",0.3341,0.5742,0.2474
15,llama2-70b,none,0.1,"60,62,64,66,68,70,72,74,76,78,80",0.3403,0.5368,0.2711
16,llama2-70b,none,0.25,"60,62,64,66,68,70,72,74,76,78,80",0.3280,0.5293,0.2631
17,llama2-70b,none,0.5,"60,62,64,66,68,70,72,74,76,78,80",0.3366,0.5467,0.2528
18,llama2-70b,none,0.75,"60,62,64,66,68,70,72,74,76,78,80",0.3378,0.5421,0.2425
19,llama2-70b,none,0.9,"60,62,64,66,68,70,72,74,76,78,80",0.3354,0.5426,0.2447
20,llama3_0-70b,none,none,baseline,0.3537,0.5579,0.2774
21,llama3_0-70b,none,0.0,"0,2,4,6,8,10,12,14,16,18,20,80",0.3537,0.5580,0.2759
22,llama3_0-70b,none,0.1,"0,2,4,6,8,10,12,14,16,18,20,80",0.2840,0.5106,0.2210
23,llama3_0-70b,none,0.1,"20,22,24,26,28,30,32,34,36,38,40,80",0.2803,0.5072,0.2201
24,llama3_0-70b,none,0.1,"40,42,44,46,48,50,52,54,56,58,60,80",0.2717,0.5064,0.2143
25,llama3_0-70b,none,0.1,"60,62,64,66,68,70,72,74,76,78,80",0.2778,0.5081,0.2246
26,llama3_0-70b,none,0.25,"0,2,4,6,8,10,12,14,16,18,20,80",0.2656,0.4753,0.2080
27,llama3_0-70b,none,0.5,"0,2,4,6,8,10,12,14,16,18,20,80",0.2338,0.4859,0.1824
28,llama3_0-70b,none,0.75,"0,2,4,6,8,10,12,14,16,18,20,80",0.2203,0.4855,0.1644
29,llama3_0-70b,none,0.9,"0,2,4,6,8,10,12,14,16,18,20,80",0.2203,0.4744,0.1571
30,qwen2-72b,none,none,baseline,0.4492,0.6350,0.3348
31,qwen2-72b,none,0.0,"40,42,44,46,48,50,52,54,56,58,60,80",0.3329,0.5771,0.3122
32,qwen2-72b,none,0.1,"0,2,4,6,8,10,12,14,16,18,20,80",0.3599,0.6000,0.2659
33,qwen2-72b,none,0.1,"20,22,24,26,28,30,32,34,36,38,40,80",0.3550,0.5959,0.2731
34,qwen2-72b,none,0.1,"40,42,44,46,48,50,52,54,56,58,60,80",0.3807,0.5968,0.2895
35,qwen2-72b,none,0.1,"60,62,64,66,68,70,72,74,76,78,80",0.2791,0.5112,0.2740
36,qwen2-72b,none,0.25,"40,42,44,46,48,50,52,54,56,58,60,80",0.3819,0.5099,0.2870
37,qwen2-72b,none,0.5,"40,42,44,46,48,50,52,54,56,58,60,80",0.3917,0.4599,0.2997
38,qwen2-72b,none,0.75,"40,42,44,46,48,50,52,54,56,58,60,80",0.3782,0.4486,0.2962
39,qwen2-72b,none,0.9,"40,42,44,46,48,50,52,54,56,58,60,80",0.3672,0.4480,0.2862

### Analyze results directory

In [6]:
import glob
raw_results = []
fps = glob.glob('../DoLa/results/tfqa_bucket_search/*/*/*/*/*res*')
for fp in fps:
    model_name = fp.split('/')[-3]
    layers = fp.split('/')[-2]
    data = json.load(open(fp))
    raw_results.append([model_name, layers, data['total_mc1'], data['total_mc2'], data['total_mc3']])
df = pd.DataFrame(raw_results, columns=['model_name', 'buckets', 'mc1', 'mc2', 'mc3'])#.query('buckets == "baseline"')

for col in df.columns:
    if isinstance(df[col].iloc[0], float):
        df[col] = df[col].apply(lambda x: round(x, 4))
print(df.model_name.unique())

df#.query('model_name == "Meta-Llama-3-70B"')

['OLMo-7B-0424-hf' 'Meta-Llama-3-8B' 'Llama-2-7b-hf' 'Mistral-7B-v0.1'
 'llama-7b' 'Qwen2-7B']

,model_name,buckets,mc1,mc2,mc3
0,OLMo-7B-0424-hf,"0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32",0.2436,0.4176,0.1779
1,OLMo-7B-0424-hf,32,0.2509,0.3957,0.1878
2,OLMo-7B-0424-hf,"0,2,4,6,8,10,12,14,16,32",0.2436,0.4176,0.1779
3,OLMo-7B-0424-hf,"10,12,14,16,18,20,22,24,32",0.2399,0.4205,0.1781
4,OLMo-7B-0424-hf,"16,18,20,22,24,26,28,30,32",0.2411,0.4193,0.1779
5,Meta-Llama-3-8B,"0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32",0.2913,0.5129,0.2253
6,Meta-Llama-3-8B,32,0.3195,0.4884,0.2392
7,Meta-Llama-3-8B,"0,2,4,6,8,10,12,14,16,32",0.2913,0.5129,0.2253
8,Meta-Llama-3-8B,"10,12,14,16,18,20,22,24,32",0.2876,0.5128,0.2236
9,Meta-Llama-3-8B,"16,18,20,22,24,26,28,30,32",0.2864,0.5113,0.2231
10,Llama-2-7b-hf,"0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32",0.2595,0.4362,0.1954
11,Llama-2-7b-hf,32,0.2852,0.4340,0.2076
12,Llama-2-7b-hf,"0,2,4,6,8,10,12,14,16,32",0.2558,0.4340,0.1935
13,Llama-2-7b-hf,"10,12,14,16,18,20,22,24,32",0.2497,0.4350,0.1914
14,Llama-2-7b-hf,"16,18,20,22,24,26,28,30,32",0.2534,0.4408,0.1929
15,Mistral-7B-v0.1,"0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32",0.2987,0.4841,0.2249
16,Mistral-7B-v0.1,32,0.3158,0.4814,0.2389
17,Mistral-7B-v0.1,"0,2,4,6,8,10,12,14,16,32",0.2987,0.4841,0.2249
18,Mistral-7B-v0.1,"10,12,14,16,18,20,22,24,32",0.2974,0.4842,0.2245
19,Mistral-7B-v0.1,"16,18,20,22,24,26,28,30,32",0.2974,0.4842,0.2245
20,llama-7b,"0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32",0.2436,0.4234,0.1824
21,llama-7b,32,0.2570,0.4055,0.1924
22,llama-7b,"0,2,4,6,8,10,12,14,16,32",0.2375,0.4061,0.1739
23,llama-7b,"10,12,14,16,18,20,22,24,32",0.2436,0.4166,0.1797
24,llama-7b,"16,18,20,22,24,26,28,30,32",0.2546,0.4414,0.1934
25,Qwen2-7B,"0,2,4,6,8,10,12,14,28",0.3550,0.4935,0.2840
26,Qwen2-7B,"0,2,4,6,8,10,12,14,16,18,20,22,24,26,28",0.3623,0.4756,0.2963
27,Qwen2-7B,"8,10,12,14,16,18,20,22,28",0.3733,0.5073,0.2988
28,Qwen2-7B,"14,16,18,20,22,24,26,28",0.3623,0.4756,0.2963
29,Qwen2-7B,28,0.3929,0.5814,0.3037

# FACTOR

### Analyze results2 directory

In [19]:
raw_results = []
dola_results_dir = '../DoLa/results2/factor/{model_name}'
for model_name in IMPLEMENTED_MODELS:
    model_results_dir = dola_results_dir.format(model_name=model_name)
    if not os.path.exists(model_results_dir):
        continue
    result_fps = sorted(glob.glob(os.path.join(
        model_results_dir, '*'
    )))
    for result_fp in result_fps:
        result_name = os.path.basename(result_fp)[:-5]
        data = json.load(open(os.path.join(result_fp)))
        score = np.mean(data['is_correct'])
        raw_results.append([model_name, result_name.split('-')[1], result_name.split('-')[3], result_name.split('-')[4], score])
df = pd.DataFrame(raw_results, columns=['model_name', 'ln_type', 'alpha', 'buckets', 'acc'])

for col in df.columns:
    if isinstance(df[col].iloc[0], float):
        df[col] = df[col].apply(lambda x: round(x, 4))
print(df.model_name.unique())
df#.query('model_name == "qwen2-72b"')

['pythia-6.9b' 'llama2-70b' 'llama3_0-70b' 'qwen2-72b']

,model_name,ln_type,alpha,buckets,acc
0,pythia-6.9b,none,none,baseline,0.5125
1,pythia-6.9b,none,0.0,"0,2,4,6,8,10,12,14,16,32",0.2828
2,pythia-6.9b,none,0.1,"0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32",0.4054
3,pythia-6.9b,none,0.1,"0,2,4,6,8,10,12,14,16,32",0.4643
4,pythia-6.9b,none,0.1,"16,18,20,22,24,26,28,30,32",0.3697
5,pythia-6.9b,none,0.1,"8,10,12,14,16,18,20,22,24,32",0.3996
6,pythia-6.9b,none,0.25,"0,2,4,6,8,10,12,14,16,32",0.4797
7,pythia-6.9b,none,0.5,"0,2,4,6,8,10,12,14,16,32",0.4788
8,pythia-6.9b,none,0.75,"0,2,4,6,8,10,12,14,16,32",0.4537
9,pythia-6.9b,none,0.9,"0,2,4,6,8,10,12,14,16,32",0.4614
10,llama2-70b,none,none,baseline,0.8320
11,llama2-70b,none,0.0,"0,2,4,6,8,10,12,14,16,18,20,80",0.8176
12,llama2-70b,none,0.1,"0,2,4,6,8,10,12,14,16,18,20,80",0.8214
13,llama2-70b,none,0.1,"20,22,24,26,28,30,32,34,36,38,40,80",0.8195
14,llama2-70b,none,0.1,"40,42,44,46,48,50,52,54,56,58,60,80",0.7635
15,llama2-70b,none,0.1,"60,62,64,66,68,70,72,74,76,78,80",0.7124
16,llama2-70b,none,0.25,"0,2,4,6,8,10,12,14,16,18,20,80",0.7983
17,llama2-70b,none,0.5,"0,2,4,6,8,10,12,14,16,18,20,80",0.7905
18,llama2-70b,none,0.75,"0,2,4,6,8,10,12,14,16,18,20,80",0.7664
19,llama2-70b,none,0.9,"0,2,4,6,8,10,12,14,16,18,20,80",0.7317
20,llama3_0-70b,none,none,baseline,0.8475
21,llama3_0-70b,none,0.0,"40,42,44,46,48,50,52,54,56,58,60,80",0.8494
22,llama3_0-70b,none,0.1,"0,2,4,6,8,10,12,14,16,18,20,80",0.8552
23,llama3_0-70b,none,0.1,"20,22,24,26,28,30,32,34,36,38,40,80",0.8562
24,llama3_0-70b,none,0.1,"40,42,44,46,48,50,52,54,56,58,60,80",0.8571
25,llama3_0-70b,none,0.1,"60,62,64,66,68,70,72,74,76,78,80",0.8514
26,llama3_0-70b,none,0.25,"40,42,44,46,48,50,52,54,56,58,60,80",0.8127
27,llama3_0-70b,none,0.5,"40,42,44,46,48,50,52,54,56,58,60,80",0.7751
28,llama3_0-70b,none,0.75,"40,42,44,46,48,50,52,54,56,58,60,80",0.7847
29,llama3_0-70b,none,0.9,"40,42,44,46,48,50,52,54,56,58,60,80",0.7558
30,qwen2-72b,none,none,baseline,0.8224
31,qwen2-72b,none,0.0,"0,2,4,6,8,10,12,14,16,18,20,80",0.8243
32,qwen2-72b,none,0.1,"0,2,4,6,8,10,12,14,16,18,20,80",0.8079
33,qwen2-72b,none,0.1,"20,22,24,26,28,30,32,34,36,38,40,80",0.8012
34,qwen2-72b,none,0.1,"40,42,44,46,48,50,52,54,56,58,60,80",0.7056
35,qwen2-72b,none,0.1,"60,62,64,66,68,70,72,74,76,78,80",0.6187
36,qwen2-72b,none,0.25,"0,2,4,6,8,10,12,14,16,18,20,80",0.7770
37,qwen2-72b,none,0.5,"0,2,4,6,8,10,12,14,16,18,20,80",0.7375
38,qwen2-72b,none,0.75,"0,2,4,6,8,10,12,14,16,18,20,80",0.7355
39,qwen2-72b,none,0.9,"0,2,4,6,8,10,12,14,16,18,20,80",0.7259

### Analyze results directory

In [25]:
import glob
raw_results = []
fps = glob.glob('../DoLa/results/factor_bucket_search/*/*/*/*res*')
for fp in fps:
    model_name = fp.split('/')[-3]
    layers = fp.split('/')[-2]
    data = json.load(open(fp))
    score = np.mean(data['is_correct'])
    raw_results.append([model_name, layers, score])
df = pd.DataFrame(raw_results, columns=['model_name', 'buckets', 'acc'])

for col in df.columns:
    if isinstance(df[col].iloc[0], float):
        df[col] = df[col].apply(lambda x: round(x, 4))
print(df.model_name.unique())
df[df['buckets'].str.len() == 2]#.query('model_name == "Qwen2-7B"')

['OLMo-7B-0424-hf' 'Meta-Llama-3-8B' 'Llama-2-70b-hf' 'Meta-Llama-3-70B'
 'Llama-2-7b-hf' 'Mistral-7B-v0.1' 'llama-7b' 'Qwen2-72B' 'Qwen2-7B'
 'pythia-6.9b']

          model_name buckets     acc
4    OLMo-7B-0424-hf      32  0.6660
7    OLMo-7B-0424-hf      28  0.3737
12   Meta-Llama-3-8B      32  0.7546
17    Llama-2-70b-hf      80  0.8106
23  Meta-Llama-3-70B      80  0.8167
30     Llama-2-7b-hf      32  0.7220
32     Llama-2-7b-hf      28  0.5692
39   Mistral-7B-v0.1      32  0.7576
42   Mistral-7B-v0.1      28  0.4104
47          llama-7b      32  0.5845
49          llama-7b      28  0.5550
53         Qwen2-72B      80  0.8106
62          Qwen2-7B      28  0.6925
67       pythia-6.9b      32  0.5132
70       pythia-6.9b      28  0.4684

# Analyzing Best Layers

In [48]:
import glob
raw_results = []
fps = glob.glob('../DoLa/results/tfqa_bucket_search/*/*/*/*/*lay*')
for fp in fps:
    model_name = fp.split('/')[-3]
    layers = fp.split('/')[-2]
    data = json.load(open(fp))
    all_layers = list(data.keys())
    all_usage = list(data.values())
    sorted_usage = np.argsort(all_usage)
    top_layer = sorted_usage[-1]
    tl_pct_used = all_usage[top_layer]/sum(data.values())
    # if len(all_layers) > 1:
    sb_layer = sorted_usage[-2]
    sbl_pct_used = all_usage[sb_layer]/sum(data.values())
    # else:
    #     sb_layer = np.nan
    #     sbl_pct_used = np.nan
    
    raw_results.append([model_name, layers, top_layer, tl_pct_used, sb_layer, sbl_pct_used])
df = pd.DataFrame(raw_results, columns=['model_name', 'buckets', 'top_layer', 'tl_pct_used', 'sb_layer', 'sbl_pct_used'])#.query('buckets == "baseline"')

for col in df.columns:
    if isinstance(df[col].iloc[0], float):
        df[col] = df[col].apply(lambda x: round(x, 4))
df.describe()

       top_layer  tl_pct_used   sb_layer  sbl_pct_used
count  40.000000    40.000000  40.000000     40.000000
mean    1.575000     0.725183   3.450000      0.115505
std     3.418558     0.204226   3.249852      0.097905
min     0.000000     0.328000   0.000000      0.003600
25%     0.000000     0.572500   1.000000      0.038550
50%     0.000000     0.747450   2.000000      0.094650
75%     0.000000     0.901800   6.000000      0.153800
max    13.000000     0.995000  12.000000      0.442800